language: java

jdk:
  - oraclejdk8

script:
  - mvn clean install jacoco:report

after_success:
  - mvn coveralls:report

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'