language: java

jdk:
  - oraclejdk8

script:
  - mvn clean install org.jacoco:jacoco-maven-plugin:prepare-agent

after_success:
  - mvn org.eluder.coveralls:coveralls-maven-plugin:report

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'