language: java

jdk:
  - oraclejdk8

addons:
  sonarqube:
    token:
      secure: "b4uzWwnrKXGM6LGE42jrr8VPvhbl/LuAOkP2Z4TGR5k8YmJHwi3JZvq23CGrdYMGmf7NdhD1JkXtlLbfn91AxE/6ioKnRZ8XLx7q1xaBB+hbFFdGod/4c6BP/m53P6h8w1rAeD8YaP5Neah4N8VLe1ldxLiGY3lcRIW83xId7ZLxI2zs+h6J9hyskUllurupGUHOxHn1v+mG+w8jl4nieVBwQ0sJAcerfn4ZRiMLRymqVRKt8rkRb9GlZUCB2o/wCmGFtQb1KqoAdlLvq2YHGNC1u2EjMjtQBlJfP3sMbrnfdbvwCjq1qlZhVkg3qzFSTo61gJH1+KBKsmABSr1FBOVPNShugRes+suCsFAj30Qe4HmjXDpR3wEw7UF9oxPD006hj0VWmvGsRSF444OR3aBPobGjd/X3Nja7mWOFiZ32N4yeHH7jJNZPQ9+atalDZc5k8IoUz41H6ZFk0ONIg5RoV0edg4CkwvqZqHSzDIL6cX9dpJpsfamRkJVNtcf7WhLU+LuncOM0/m9AlZpDHjjoTrxRNsr+Cq2Dn+swBLV5igalaNkXOyFMhr4MppBrx3n99dyOyjSBOvgtjg2AoJg/8+pfoFKaVq7SwKKgb7vMe4iTO9qr57n4BiIBiqpFy4xhtr9CI5TcY8CVw1pOaiFSlEUl/JtqQfFiha7shes="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'